//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatTracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class ofMessageArchive
    {
        public long conversationID { get; set; }
        public string fromJID { get; set; }
        public string toJID { get; set; }
        public long sentDate { get; set; }
        public string body { get; set; }
    }
}
